name: ci
on:
    pull_request_target:
        branches:
            - dev
jobs:
    lint_and_build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: npm ci
            - name: Run eslint
              run: npm run eslint
            - name: Run stylelint
              run: npm run stylelint
            - name: Run build
              run: npm run build
