name: ci
on:
    pull_request:
        branches:
            - dev
jobs:
    lint_and_build:
        runs-on: [self-hosted, linux]
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: npm ci
            - name: Run eslint
              run: npx eslint
            - name: Run stylelint
              run: npx stylelint
            - name: Run build
              run: npm run build
